---
trigger:  
  - develop 

pool: 
  name: default 

resources:
  repositories:
    - repository: dockerfile 
      name: Nagaraju11111/learninggit 
      type: github 
      endpoint: github_id 
      ref: 'refs/heads/main'  
    

stages:
  - stage: build 
    jobs:
      - job: imagebuild 
        steps:
          - checkout: dockerfile 
          - task: Docker@2
            inputs:
              containerRegistry: acr_id 
              repository: src
              command: 'buildAndPush' 
              Dockerfile: 'azuredevops/Dockerfile' 
              tags: '$(Build.BuildId)'
  - stage: Deploy
    jobs:
      - job: imagedeploy 
        steps:
          - task: Kubernetes@1 
            inputs: 
              connectionType: Kubernetes Service Connection 
              kubernetesServiceEndpoint : k8s_id 
              command: apply 
              useConfigurationFile: true 
              configurationType: configuration 
              configuration: k8s/depolyment.yaml            
          

  
