---
trigger:  
  - master
pool: DOCKER
stages:
  - stage: image
    jobs:
      - job: imagebuild
        steps:
          - script: | 
              docker image build -t src2:1.0 .
              docker image tag src2:1.0 9052171017/src2:1.0
              docker image push 9052171017/src2:1.0
  - stage: container
    jobs:
      - job: containercreate
        steps:
          - script: |
              docker image ls
              docker image pull 9052171017/src2:1.0
              docker container run -d -P --name sc1 9052171017/src2:1.0
