---
trigger:  
  - develop 

pool: default

stages:
  - stage: build 
    jobs:
      - job: imagebuild
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: acr_id 
              repository: qtdevops407.azurecr.io/src
              command: 'buildAndPush' 
              Dockerfile: 'Dockerfile' 
              tags: | 
                '$(Build.BuildNumber)'

  
