--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: src-app
spec:
  minReadySeconds: 10
  replicas: 4
  selector:
    matchLabels:
      app: srcapp 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: srcapp 
      labels:
        app: srcapp  
        ver: "1.0"
    spec:
      containers:
        - image: 9052171017/srcdev:1.0
          name: app-container
          ports:
            - containerPort: 8080
              name: src 
              protocol: TCP
          env:
            - name: MYSQL_USER
              value: src-cip
          
---
apiVersion: v1
kind: Service
metadata:
  name: src-lb 
spec:
  type: LoadBalancer
  selector:
    app: srcapp 
  ports:
     - name: db-port
       port: 2500
       protocol: TCP
       targetPort: 8080